#!/bin/sh

sxhkd &

picom -b

bspc config focused_border_color "#e5e9f0"
bspc config normal_border_color "#2e3440"

bspc config border_width         1
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Application rules

bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


bspc monitor eDP1 -d I II III IV V
bspc monitor HDMI2 -d VI VII VIII IX X

