#!/bin/sh

sxhkd &

compton -b --config ~/.config/compton.conf


bspc config focused_border_color "#d5c4a1"
bspc config normal_border_color "#32302f"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Application rules

bspc rule -a Zathura state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-2 -d VI VII VIII IX X

